server:
  port: 8080

spring:
  application:
    name: MoneyMinder

  datasource:
    url: jdbc:postgresql://localhost:5432/moneyminder
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
