server:
  port: 8080

spring:
  application:
    name: MoneyMinder

  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/moneyminder
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: soufianboushaba12@gmail.com
    password: rbcf wuhr ejpx nfhi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
